### ISSUE TITLE
Simplification proposal

### ISSUE THREAD

**Issue by kasparthommen** [twiecki/covid19#1]
Hi @twiecki,

I don't think there's a need to fully clone the John Hopkins repo. It is in fact sufficient to pull the raw data as follows:

```python
import requests

...

base_url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series'

...

def load_timeseries(name):
    url = f'{base_url}/time_series_19-covid-{name}.csv'
    csv = requests.get(url, proxies=proxies).text
    df = pd.read_csv(io.StringIO(csv), index_col=['Country/Region', 'Province/State', 'Lat', 'Long'], parse_dates=True)
    ...
```

Note that I have split the reading of the CSV text and the pandas parsing into two steps because I'm behind a corporate firewall and need proxies. You could combine the two into one by directly specifying the url in the call to `pd.read_csv()`.

**Comment by twiecki** [comment]
Hi @kasparthommen. Thanks, that makes sense.

**Comment by twiecki** [comment]
Implemented.

**Comment by kasparthommen** [comment]
:+1:
