### ISSUE TITLE
Altair chart not showing

### ISSUE THREAD

**Issue by rizman18** [twiecki/covid19#16]
Yesterday, I can run all of the cells.
But, today I can't show the altair chart. Please, give me some advice.
Thanks

**Comment by hamelsmu** [comment]
@rizman18 you can see https://github.com/machine-learning-apps/covid19-dashboard/blob/master/_notebooks/2020-03-16-covid19_growth_bayes.ipynb in the meantime.  

We are working on a way to better integrate these repos.  

cc: @twiecki
