### ISSUE TITLE
Some explaination

### ISSUE THREAD

**Issue by henfri** [twiecki/covid19#18]
Hello,

I am missing some explaination for the bayes part (covid19_growth_bayes.ipynb)
What are the underlying assumptions of the prediction? 

Regards,
Hendrik

**Comment by hamelsmu** [comment]
From the notebook

> The model that we are building assumes exponential growth. This is definitely wrong because growth would just continue uninterrupted into the future. However, in the early phase of an epidemic it's a reasonable assumption.1

> We assume a negative binomial likelihood as we are dealing with count data. A Poisson could also be used but the negative binomial allows us to also model the variance separately to give more flexibility.

> The model is also hierarchical, pooling information from individual countries.

**Comment by twiecki** [comment]
Thanks @hamelsmu!

**Comment by twiecki** [comment]
@henfri let me know ify ou ahve more questions.

**Comment by henfri** [comment]
Hello,

thank you. I would like to know, what part of the data is used for training?
If you use everything except the last two days, a good fit is not surprising. If you used only half of the available days for training, and the rest is a prediction, then a good fit is remarkable.
Altogether there is very little explaination of the assumptions that you take and I would recommend putting that before the first pictures.

On the Posterior of daily growth, the y-axis is not described. I assume it is the probability?

Greetings,
Hendrik

**Comment by twiecki** [comment]
@henfri agreed on assumptions. There is no hold-out testing here but that would be interesting to do, especially since the time I first built the model until now. Let me know if you want to play around with that as I might not get around to it for some time.
